spring:
  application:
    name: service-center
  datasource:
    url: jdbc:postgresql://servicecenterbd-service-center.c.aivencloud.com:17990/servicecenterbd?sslmode=require
    username: USER
    password: PWD
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8585